[package]
name = "sks"
version = "0.0.1"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"

[dependencies]
Boa = { version = "0.6.0", default-features = false }
image = "0.23.0"
